import type { Ship } from "../types/Ship";
import { getShipImages } from "../utils/imageUtils";

export const shipsData: Ship[] = [
  {
    id: "starling-courier",
    name: "Starling Courier",
    role: "Explorer",
    className: "A-Class",
    manufacturer: "AstraWorks",
    size: "Small",
    rarity: "Uncommon",
    crewCapacity: 2,
    priceCredits: 145_000,
    drive: "Warp",
    hardpoints: 2,
    stats: {
      speed: 78,
      maneuver: 86,
      cargo: 18,
      shield: 52,
      hull: 48,
      jumpRange: 24,
    },
    tags: ["sleek", "white-blue", "lightweight", "survey nose", "tri-fin tail"],
    images: getShipImages("starling-courier"),
  },
  {
    id: "wraith-interceptor",
    name: "Wraith Interceptor",
    role: "Interceptor",
    className: "S-Class",
    manufacturer: "Nyx Dynamics",
    size: "Small",
    rarity: "Epic",
    crewCapacity: 1,
    priceCredits: 420_000,
    drive: "Quantum",
    hardpoints: 4,
    stats: {
      speed: 92,
      maneuver: 91,
      cargo: 8,
      shield: 66,
      hull: 54,
      jumpRange: 18,
    },
    tags: [
      "stealth angles",
      "matte-black",
      "neon-violet accents",
      "forward canards",
    ],
    images: getShipImages("wraith-interceptor"),
  },
  {
    id: "nomad-hauler",
    name: "Nomad Hauler",
    role: "Hauler",
    className: "B-Class",
    manufacturer: "Kovacs Transit",
    size: "Medium",
    rarity: "Common",
    crewCapacity: 6,
    priceCredits: 210_000,
    drive: "Warp",
    hardpoints: 2,
    stats: {
      speed: 48,
      maneuver: 42,
      cargo: 96,
      shield: 58,
      hull: 72,
      jumpRange: 16,
    },
    tags: ["boxy cargo pods", "industrial-yellow", "external struts", "grimy"],
    images: getShipImages("nomad-hauler"),
  },
  {
    id: "aurora-pathfinder",
    name: "Aurora Pathfinder",
    role: "Explorer",
    className: "S-Class",
    manufacturer: "Solace Aerion",
    size: "Medium",
    rarity: "Legendary",
    crewCapacity: 4,
    priceCredits: 890_000,
    drive: "Slipstream",
    hardpoints: 3,
    stats: {
      speed: 84,
      maneuver: 76,
      cargo: 28,
      shield: 82,
      hull: 70,
      jumpRange: 42,
    },
    tags: ["pearlescent", "gold trim", "wide canopy", "ringed-engine nacelles"],
    images: getShipImages("aurora-pathfinder"),
  },
  {
    id: "oryx-dredger",
    name: "Oryx Dredger",
    role: "Miner",
    className: "A-Class",
    manufacturer: "Borealis Forge",
    size: "Large",
    rarity: "Rare",
    crewCapacity: 10,
    priceCredits: 560_000,
    drive: "Warp",
    hardpoints: 3,
    stats: {
      speed: 36,
      maneuver: 28,
      cargo: 88,
      shield: 74,
      hull: 88,
      jumpRange: 14,
    },
    tags: ["massive drill", "armored prow", "hazard stripes", "plasma cutters"],
    images: getShipImages("oryx-dredger"),
  },
  {
    id: "seraph-lifeline",
    name: "Seraph Lifeline",
    role: "Medic",
    className: "A-Class",
    manufacturer: "Helion Carefleet",
    size: "Medium",
    rarity: "Uncommon",
    crewCapacity: 5,
    priceCredits: 300_000,
    drive: "Quantum",
    hardpoints: 1,
    stats: {
      speed: 64,
      maneuver: 70,
      cargo: 20,
      shield: 88,
      hull: 60,
      jumpRange: 22,
    },
    tags: ["white-red", "med-cross livery", "clean hull", "soft lighting"],
    images: getShipImages("seraph-lifeline"),
  },
  {
    id: "wayfarer-shuttle",
    name: "Wayfarer Shuttle",
    role: "Shuttle",
    className: "C-Class",
    manufacturer: "Orbital Common",
    size: "Small",
    rarity: "Common",
    crewCapacity: 2,
    priceCredits: 65_000,
    drive: "Warp",
    hardpoints: 0,
    stats: {
      speed: 52,
      maneuver: 58,
      cargo: 16,
      shield: 34,
      hull: 40,
      jumpRange: 12,
    },
    tags: ["utility", "orange-white", "short-hop", "stubby wings"],
    images: getShipImages("wayfarer-shuttle"),
  },
  {
    id: "eclipse-veil",
    name: "Eclipse Veil",
    role: "Stealth",
    className: "S-Class",
    manufacturer: "Nyx Dynamics",
    size: "Small",
    rarity: "Epic",
    crewCapacity: 1,
    priceCredits: 500_000,
    drive: "Slipstream",
    hardpoints: 2,
    stats: {
      speed: 88,
      maneuver: 95,
      cargo: 6,
      shield: 50,
      hull: 46,
      jumpRange: 26,
    },
    tags: [
      "faceted hull",
      "dark chrome",
      "blue subsurface glow",
      "sensor baffles",
    ],
    images: getShipImages("eclipse-veil"),
  },
  {
    id: "leviathan-carrier",
    name: "Leviathan Carrier",
    role: "Freighter",
    className: "A-Class",
    manufacturer: "Titan Arc",
    size: "Large",
    rarity: "Rare",
    crewCapacity: 24,
    priceCredits: 1_450_000,
    drive: "Warp",
    hardpoints: 6,
    stats: {
      speed: 22,
      maneuver: 18,
      cargo: 160,
      shield: 90,
      hull: 96,
      jumpRange: 20,
    },
    tags: ["superstructure", "hangar bays", "goliath", "beacon lights"],
    images: getShipImages("leviathan-carrier"),
  },
  {
    id: "tempest-vrx",
    name: "Tempest VRX",
    role: "Racer",
    className: "S-Class",
    manufacturer: "AstraWorks",
    size: "Small",
    rarity: "Legendary",
    crewCapacity: 1,
    priceCredits: 720_000,
    drive: "Quantum",
    hardpoints: 1,
    stats: {
      speed: 98,
      maneuver: 88,
      cargo: 4,
      shield: 44,
      hull: 42,
      jumpRange: 16,
    },
    tags: [
      "neon cyan",
      "sleek wedge",
      "open radiator fins",
      "afterburner cones",
    ],
    images: getShipImages("tempest-vrx"),
  },
];
